### ISSUE TITLE
sys_func_7 && _reorg_subgroups error and redesign

### ISSUE THREAD

**Issue by JamesonWelch** [joshuad31/tandapay-simulation2#1]
## 1. Subgroup reorg bug
The `TandaPaySimulatorV2` method `_reorg_subgroups` lines 451-457 never get executed in all of our normal starting variable tests. There seems to be a bug in how the `if` statements get evaluated to where they never trigger the nested block when they should. This error could be resolved by the next subtask

## 2. Refactor System Function 7 to use defined paths for readability
Refactor `sys_func_7` and `_reorg_subgroups` so each path is explicitly defined and each `if` statement can be followed with relative quickness in debugging processes.

**Comment by openedhardware** [comment]
@JamesonWelch 

`_reorg_subgroups` function is called in the `sys_func_7` function:
```python
    def sys_func_7(self):
        """"
        Reorganization of Users
        """
        for i in [3, 2, 1]:
            for j in range(3):
                while self._reorg_subgroups(i, 5 + j - i):
                    pass
```

- At first, it tries to reorganize 3 & 2(i = 3, j = 0), resulting in a group of 5. 
- If no groups of two exists(`_reorg_subgroups()` function does return `None`), move to next(i = 3, j = 1), which tries to reorganize 3 & 3.
- ... ... ...
